"""Audiobook catalog — 125 books (66 French + 59 English), all public domain.

Each entry maps a short CLI name to metadata used by stream_tone.py and fetch_books.py.
Voice is auto-selected by language: Thomas (fr) or Alex (en).
"""

BOOK_CATALOG = {

    # ══════════════════════════════════════════════════════════════════
    #  ENGLISH CLASSICS (36 EN + 14 FR originals = 50 original books)
    # ══════════════════════════════════════════════════════════════════

    # ── Stoic Philosophy (5) ──────────────────────────────────────────
    "meditations": {
        "title": "Meditations",
        "author": "Marcus Aurelius",
        "gutenberg_id": 2680,
        "voice": "Alex",
        "language": "en",
        "category": "Stoic Philosophy",
    },
    "enchiridion": {
        "title": "The Enchiridion",
        "author": "Epictetus",
        "gutenberg_id": 45109,
        "voice": "Alex",
        "language": "en",
        "category": "Stoic Philosophy",
    },
    "lettres-lucilius": {
        "title": "Minor Dialogues (inc. On Shortness of Life)",
        "author": "Seneca",
        "gutenberg_id": 64576,
        "voice": "Alex",
        "language": "en",
        "category": "Stoic Philosophy",
    },
    "golden-sayings-epictetus": {
        "title": "Golden Sayings of Epictetus",
        "author": "Epictetus",
        "gutenberg_id": 871,
        "voice": "Alex",
        "language": "en",
        "category": "Stoic Philosophy",
    },

    # ── Greek Philosophy (7) ──────────────────────────────────────────
    "republique": {
        "title": "The Republic",
        "author": "Plato",
        "gutenberg_id": 1497,
        "voice": "Alex",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "apologie": {
        "title": "Apology",
        "author": "Plato",
        "gutenberg_id": 1656,
        "voice": "Alex",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "banquet": {
        "title": "Symposium",
        "author": "Plato",
        "gutenberg_id": 1600,
        "voice": "Alex",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "phedon": {
        "title": "Phaedo",
        "author": "Plato",
        "gutenberg_id": 1658,
        "voice": "Alex",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "phedre": {
        "title": "Phaedrus",
        "author": "Plato",
        "gutenberg_id": 1636,
        "voice": "Alex",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "gorgias": {
        "title": "Gorgias",
        "author": "Plato",
        "gutenberg_id": 1672,
        "voice": "Alex",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "ethique-nicomaque": {
        "title": "Nicomachean Ethics",
        "author": "Aristotle",
        "gutenberg_id": 8438,
        "voice": "Alex",
        "language": "en",
        "category": "Greek Philosophy",
    },

    # ── Eastern Philosophy & Wisdom (5) ───────────────────────────────
    "art-guerre": {
        "title": "The Art of War",
        "author": "Sun Tzu",
        "gutenberg_id": 132,
        "voice": "Alex",
        "language": "en",
        "category": "Eastern Philosophy",
    },
    "tao-te-king": {
        "title": "Tao Te Ching",
        "author": "Lao Tzu",
        "gutenberg_id": 216,
        "voice": "Alex",
        "language": "en",
        "category": "Eastern Philosophy",
    },
    "dhammapada": {
        "title": "Dhammapada",
        "author": "Buddha",
        "gutenberg_id": 2017,
        "voice": "Alex",
        "language": "en",
        "category": "Eastern Philosophy",
    },
    "bhagavad-gita": {
        "title": "Bhagavad-Gita",
        "author": "Vyasa",
        "gutenberg_id": 2388,
        "voice": "Alex",
        "language": "en",
        "category": "Eastern Philosophy",
    },
    "entretiens-confucius": {
        "title": "Les quatre livres de philosophie",
        "author": "Confucius",
        "gutenberg_id": 44958,
        "voice": "Thomas",
        "language": "fr",
        "category": "Eastern Philosophy",
    },

    # ── Japanese Wisdom (2) ───────────────────────────────────────────
    "bushido": {
        "title": "Bushido, the Soul of Japan",
        "author": "Inazo Nitobe",
        "gutenberg_id": 12096,
        "voice": "Alex",
        "language": "en",
        "category": "Japanese Wisdom",
    },

    # ── Religious Texts (2) ───────────────────────────────────────────
    "bible": {
        "title": "The Bible (King James Version)",
        "author": "King James",
        "gutenberg_id": 10,
        "voice": "Alex",
        "language": "en",
        "category": "Religious Texts",
    },
    "coran": {
        "title": "The Quran",
        "author": "tr. Rodwell",
        "gutenberg_id": 2800,
        "voice": "Alex",
        "language": "en",
        "category": "Religious Texts",
    },

    # ── French Philosophy (6) — originals in French! ─────────────────
    "essais": {
        "title": "Essais",
        "author": "Montaigne",
        "gutenberg_id": 48529,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },
    "discours-methode": {
        "title": "Discours de la méthode",
        "author": "Descartes",
        "gutenberg_id": 13846,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },
    "pensees": {
        "title": "Pensées",
        "author": "Pascal",
        "gutenberg_id": 46921,
        "voice": "Alex",
        "language": "en",
        "category": "French Philosophy",
    },
    "prince": {
        "title": "The Prince",
        "author": "Machiavelli",
        "gutenberg_id": 1232,
        "voice": "Alex",
        "language": "en",
        "category": "French Philosophy",
    },
    "contrat-social": {
        "title": "The Social Contract",
        "author": "Rousseau",
        "gutenberg_id": 46333,
        "voice": "Alex",
        "language": "en",
        "category": "French Philosophy",
    },
    "oracle-manuel": {
        "title": "The Art of Controversy",
        "author": "Schopenhauer",
        "gutenberg_id": 10731,
        "voice": "Alex",
        "language": "en",
        "category": "French Philosophy",
    },

    # ── German Philosophy in French (3) ──────────────────────────────
    "zarathoustra": {
        "title": "Ainsi parlait Zarathoustra",
        "author": "Nietzsche",
        "gutenberg_id": 5258,
        "voice": "Thomas",
        "language": "fr",
        "category": "German Philosophy",
    },
    "bien-mal": {
        "title": "Beyond Good and Evil",
        "author": "Nietzsche",
        "gutenberg_id": 4363,
        "voice": "Alex",
        "language": "en",
        "category": "German Philosophy",
    },

    # ── French Literature (8) — originals in French! ─────────────────
    "candide": {
        "title": "Candide",
        "author": "Voltaire",
        "gutenberg_id": 4650,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "fables": {
        "title": "Les Fables",
        "author": "La Fontaine",
        "gutenberg_id": 56327,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "fleurs-mal": {
        "title": "Les Fleurs du mal",
        "author": "Baudelaire",
        "gutenberg_id": 6099,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "miserables": {
        "title": "Les Misérables",
        "author": "Victor Hugo",
        "gutenberg_id": 17489,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "monte-cristo": {
        "title": "Le Comte de Monte-Cristo",
        "author": "Alexandre Dumas",
        "gutenberg_id": 17989,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "trois-mousquetaires": {
        "title": "Les Trois Mousquetaires",
        "author": "Alexandre Dumas",
        "gutenberg_id": 13951,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "cyrano": {
        "title": "Cyrano de Bergerac",
        "author": "Edmond Rostand",
        "gutenberg_id": 1256,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },

    # ── Classical Literature (5) ──────────────────────────────────────
    "odyssee": {
        "title": "L'Odyssée",
        "author": "Homère",
        "gutenberg_id": 14286,
        "voice": "Thomas",
        "language": "fr",
        "category": "Classical Literature",
    },
    "iliade": {
        "title": "L'Iliade",
        "author": "Homère",
        "gutenberg_id": 14285,
        "voice": "Thomas",
        "language": "fr",
        "category": "Classical Literature",
    },
    "eneide": {
        "title": "The Aeneid",
        "author": "Virgil",
        "gutenberg_id": 228,
        "voice": "Alex",
        "language": "en",
        "category": "Classical Literature",
    },
    "metamorphoses": {
        "title": "The Metamorphoses",
        "author": "Ovid",
        "gutenberg_id": 21765,
        "voice": "Alex",
        "language": "en",
        "category": "Classical Literature",
    },
    "nature-choses": {
        "title": "On the Nature of Things",
        "author": "Lucretius",
        "gutenberg_id": 785,
        "voice": "Alex",
        "language": "en",
        "category": "Classical Literature",
    },

    # ── Roman Wisdom (2) ─────────────────────────────────────────────
    "amitie": {
        "title": "Treatises on Friendship and Old Age",
        "author": "Cicero",
        "gutenberg_id": 2808,
        "voice": "Alex",
        "language": "en",
        "category": "Roman Wisdom",
    },

    # ── Persian & Eastern Poetry (2) ──────────────────────────────────
    "rubaiyat": {
        "title": "Rubaiyat of Omar Khayyam",
        "author": "Omar Khayyam",
        "gutenberg_id": 246,
        "voice": "Alex",
        "language": "en",
        "category": "Persian & Eastern Poetry",
    },

    # ── Spiritual Classics (3) ───────────────────────────────────────
    "imitation": {
        "title": "L'Imitation de Jésus-Christ",
        "author": "Thomas a Kempis",
        "gutenberg_id": 57824,
        "voice": "Thomas",
        "language": "fr",
        "category": "Spiritual Classics",
    },

    # ══════════════════════════════════════════════════════════════════
    #  FRENCH LITERATURE — 36 verified French books from Gutenberg
    # ══════════════════════════════════════════════════════════════════

    # ── French Novels ────────────────────────────────────────────────
    "madame-bovary": {
        "title": "Madame Bovary",
        "author": "Gustave Flaubert",
        "gutenberg_id": 14155,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "rouge-et-noir": {
        "title": "Le rouge et le noir",
        "author": "Stendhal",
        "gutenberg_id": 798,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "chartreuse-de-parme": {
        "title": "La Chartreuse de Parme",
        "author": "Stendhal",
        "gutenberg_id": 796,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "eugenie-grandet": {
        "title": "Eugénie Grandet",
        "author": "Honoré de Balzac",
        "gutenberg_id": 11049,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "germinal": {
        "title": "Germinal",
        "author": "Émile Zola",
        "gutenberg_id": 5711,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "nana": {
        "title": "Nana",
        "author": "Émile Zola",
        "gutenberg_id": 5250,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "assommoir": {
        "title": "L'Assommoir",
        "author": "Émile Zola",
        "gutenberg_id": 6497,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "therese-raquin": {
        "title": "Thérèse Raquin",
        "author": "Émile Zola",
        "gutenberg_id": 7461,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "notre-dame-de-paris": {
        "title": "Notre-Dame de Paris",
        "author": "Victor Hugo",
        "gutenberg_id": 19657,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "homme-qui-rit": {
        "title": "L'homme qui rit",
        "author": "Victor Hugo",
        "gutenberg_id": 5423,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "quatrevingt-treize": {
        "title": "Quatrevingt-Treize",
        "author": "Victor Hugo",
        "gutenberg_id": 9645,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "dame-aux-camelias": {
        "title": "La dame aux camélias",
        "author": "Alexandre Dumas fils",
        "gutenberg_id": 2419,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "liaisons-dangereuses": {
        "title": "Les liaisons dangereuses",
        "author": "Choderlos de Laclos",
        "gutenberg_id": 52006,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "grand-meaulnes": {
        "title": "Le Grand Meaulnes",
        "author": "Alain-Fournier",
        "gutenberg_id": 5781,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "fantome-opera": {
        "title": "Le Fantôme de l'Opéra",
        "author": "Gaston Leroux",
        "gutenberg_id": 62215,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "arsene-lupin": {
        "title": "Arsène Lupin, gentleman-cambrioleur",
        "author": "Maurice Leblanc",
        "gutenberg_id": 32854,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "petite-fadette": {
        "title": "La petite Fadette",
        "author": "George Sand",
        "gutenberg_id": 34204,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "a-rebours": {
        "title": "À rebours",
        "author": "J.-K. Huysmans",
        "gutenberg_id": 56149,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "du-cote-de-chez-swann": {
        "title": "Du côté de chez Swann",
        "author": "Marcel Proust",
        "gutenberg_id": 2650,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },

    # ── Jules Verne ──────────────────────────────────────────────────
    "tour-du-monde": {
        "title": "Le tour du monde en quatre-vingts jours",
        "author": "Jules Verne",
        "gutenberg_id": 800,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },
    "voyage-centre-terre": {
        "title": "Voyage au centre de la Terre",
        "author": "Jules Verne",
        "gutenberg_id": 4791,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },
    "vingt-mille-lieues": {
        "title": "Vingt mille lieues sous les mers",
        "author": "Jules Verne",
        "gutenberg_id": 5097,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },
    "ile-mysterieuse": {
        "title": "L'île mystérieuse",
        "author": "Jules Verne",
        "gutenberg_id": 14287,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },
    "de-la-terre-a-la-lune": {
        "title": "De la terre à la lune",
        "author": "Jules Verne",
        "gutenberg_id": 38674,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },

    # ── French Theatre ───────────────────────────────────────────────
    "avare": {
        "title": "L'Avare",
        "author": "Molière",
        "gutenberg_id": 6318,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Theatre",
    },
    "don-juan": {
        "title": "Don Juan, ou le Festin de pierre",
        "author": "Molière",
        "gutenberg_id": 5130,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Theatre",
    },
    "hernani": {
        "title": "Hernani",
        "author": "Victor Hugo",
        "gutenberg_id": 9976,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Theatre",
    },

    # ── French Poetry ────────────────────────────────────────────────
    "alcools": {
        "title": "Alcools",
        "author": "Guillaume Apollinaire",
        "gutenberg_id": 15462,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Poetry",
    },
    "poesies-rimbaud": {
        "title": "Poésies complètes",
        "author": "Arthur Rimbaud",
        "gutenberg_id": 29302,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Poetry",
    },
    "verlaine-oeuvres": {
        "title": "Œuvres complètes, Volume 1",
        "author": "Paul Verlaine",
        "gutenberg_id": 15112,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Poetry",
    },
    "legende-des-siecles": {
        "title": "La Légende des siècles",
        "author": "Victor Hugo",
        "gutenberg_id": 12137,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Poetry",
    },

    # ── French Short Stories ─────────────────────────────────────────
    "boule-de-suif": {
        "title": "Boule de Suif",
        "author": "Guy de Maupassant",
        "gutenberg_id": 10746,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Short Stories",
    },
    "le-horla": {
        "title": "Le Horla",
        "author": "Guy de Maupassant",
        "gutenberg_id": 10775,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Short Stories",
    },
    "contes-de-perrault": {
        "title": "Histoires ou Contes du temps passé",
        "author": "Charles Perrault",
        "gutenberg_id": 20972,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Short Stories",
    },
    "lettres-de-mon-moulin": {
        "title": "Lettres de mon moulin",
        "author": "Alphonse Daudet",
        "gutenberg_id": 36780,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Short Stories",
    },

    # ── French Philosophy (additional) ───────────────────────────────
    "traite-tolerance": {
        "title": "Traité sur la tolérance",
        "author": "Voltaire",
        "gutenberg_id": 42131,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy (additional)",
    },

    # ══════════════════════════════════════════════════════════════════
    #  MINDFULNESS, SELF-IMPROVEMENT & PERSONAL GROWTH — 50 new books
    # ══════════════════════════════════════════════════════════════════

    # ── Mindfulness & Inner Peace (EN) ──────────────────────────────
    "walden": {
        "title": "Walden, or Life in the Woods",
        "author": "Henry David Thoreau",
        "gutenberg_id": 205,
        "voice": "Alex",
        "language": "en",
        "category": "Mindfulness & Inner Peace",
    },
    "as-a-man-thinketh": {
        "title": "As a Man Thinketh",
        "author": "James Allen",
        "gutenberg_id": 4507,
        "voice": "Alex",
        "language": "en",
        "category": "Mindfulness & Inner Peace",
    },
    "way-of-peace": {
        "title": "The Way of Peace",
        "author": "James Allen",
        "gutenberg_id": 3465,
        "voice": "Alex",
        "language": "en",
        "category": "Mindfulness & Inner Peace",
    },
    "self-help-smiles": {
        "title": "Self-Help",
        "author": "Samuel Smiles",
        "gutenberg_id": 935,
        "voice": "Alex",
        "language": "en",
        "category": "Mindfulness & Inner Peace",
    },
    "how-to-live-24h": {
        "title": "How to Live on 24 Hours a Day",
        "author": "Arnold Bennett",
        "gutenberg_id": 2274,
        "voice": "Alex",
        "language": "en",
        "category": "Mindfulness & Inner Peace",
    },
    "power-concentration": {
        "title": "The Power of Concentration",
        "author": "Theron Q. Dumont",
        "gutenberg_id": 35477,
        "voice": "Alex",
        "language": "en",
        "category": "Mindfulness & Inner Peace",
    },
    "problems-philosophy": {
        "title": "The Problems of Philosophy",
        "author": "Bertrand Russell",
        "gutenberg_id": 5827,
        "voice": "Alex",
        "language": "en",
        "category": "Mindfulness & Inner Peace",
    },
    "varieties-religious": {
        "title": "The Varieties of Religious Experience",
        "author": "William James",
        "gutenberg_id": 621,
        "voice": "Alex",
        "language": "en",
        "category": "Mindfulness & Inner Peace",
    },
    "pragmatism": {
        "title": "Pragmatism",
        "author": "William James",
        "gutenberg_id": 5116,
        "voice": "Alex",
        "language": "en",
        "category": "Mindfulness & Inner Peace",
    },

    # ── Transcendentalism & Nature (EN) ─────────────────────────────
    "emerson-essays": {
        "title": "Essays, First Series",
        "author": "Ralph Waldo Emerson",
        "gutenberg_id": 2944,
        "voice": "Alex",
        "language": "en",
        "category": "Transcendentalism & Nature",
    },
    "nature-emerson": {
        "title": "Nature",
        "author": "Ralph Waldo Emerson",
        "gutenberg_id": 29433,
        "voice": "Alex",
        "language": "en",
        "category": "Transcendentalism & Nature",
    },
    "civil-disobedience": {
        "title": "On the Duty of Civil Disobedience",
        "author": "Henry David Thoreau",
        "gutenberg_id": 71,
        "voice": "Alex",
        "language": "en",
        "category": "Transcendentalism & Nature",
    },
    "leaves-of-grass": {
        "title": "Leaves of Grass",
        "author": "Walt Whitman",
        "gutenberg_id": 1322,
        "voice": "Alex",
        "language": "en",
        "category": "Transcendentalism & Nature",
    },
    "songs-innocence": {
        "title": "Songs of Innocence and of Experience",
        "author": "William Blake",
        "gutenberg_id": 1934,
        "voice": "Alex",
        "language": "en",
        "category": "Transcendentalism & Nature",
    },

    # ── Spiritual Wisdom (EN) ───────────────────────────────────────
    "imitation-christ-en": {
        "title": "The Imitation of Christ",
        "author": "Thomas a Kempis",
        "gutenberg_id": 1653,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },
    "confessions-augustine": {
        "title": "The Confessions of St. Augustine",
        "author": "Saint Augustine",
        "gutenberg_id": 3296,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },
    "prophet-gibran": {
        "title": "The Prophet",
        "author": "Kahlil Gibran",
        "gutenberg_id": 58585,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },
    "gospel-buddha": {
        "title": "The Gospel of Buddha",
        "author": "Paul Carus",
        "gutenberg_id": 35895,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },
    "gitanjali": {
        "title": "Gitanjali",
        "author": "Rabindranath Tagore",
        "gutenberg_id": 7164,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },
    "sadhana": {
        "title": "Sadhana, The Realisation of Life",
        "author": "Rabindranath Tagore",
        "gutenberg_id": 7166,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },
    "songs-kabir": {
        "title": "Songs of Kabîr",
        "author": "Rabindranath Tagore (tr.)",
        "gutenberg_id": 6519,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },
    "paradise-lost": {
        "title": "Paradise Lost",
        "author": "John Milton",
        "gutenberg_id": 26,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },
    "divine-comedy": {
        "title": "The Divine Comedy",
        "author": "Dante Alighieri (Longfellow tr.)",
        "gutenberg_id": 1004,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },
    "pilgrim-progress": {
        "title": "The Pilgrim's Progress",
        "author": "John Bunyan",
        "gutenberg_id": 131,
        "voice": "Alex",
        "language": "en",
        "category": "Spiritual Wisdom",
    },

    # ── Literature on the Human Condition (EN) ──────────────────────
    "crime-punishment": {
        "title": "Crime and Punishment",
        "author": "Fyodor Dostoyevsky",
        "gutenberg_id": 2554,
        "voice": "Alex",
        "language": "en",
        "category": "Human Condition",
    },
    "brothers-karamazov": {
        "title": "The Brothers Karamazov",
        "author": "Fyodor Dostoyevsky",
        "gutenberg_id": 28054,
        "voice": "Alex",
        "language": "en",
        "category": "Human Condition",
    },
    "anna-karenina": {
        "title": "Anna Karenina",
        "author": "Leo Tolstoy",
        "gutenberg_id": 1399,
        "voice": "Alex",
        "language": "en",
        "category": "Human Condition",
    },
    "war-and-peace": {
        "title": "War and Peace",
        "author": "Leo Tolstoy",
        "gutenberg_id": 2600,
        "voice": "Alex",
        "language": "en",
        "category": "Human Condition",
    },
    "death-ivan-ilyich": {
        "title": "The Death of Ivan Ilyich",
        "author": "Leo Tolstoy",
        "gutenberg_id": 927,
        "voice": "Alex",
        "language": "en",
        "category": "Human Condition",
    },
    "resurrection-tolstoy": {
        "title": "Resurrection",
        "author": "Leo Tolstoy",
        "gutenberg_id": 1938,
        "voice": "Alex",
        "language": "en",
        "category": "Human Condition",
    },
    "tale-two-cities": {
        "title": "A Tale of Two Cities",
        "author": "Charles Dickens",
        "gutenberg_id": 98,
        "voice": "Alex",
        "language": "en",
        "category": "Human Condition",
    },

    # ── French Classics — Philosophy & Wisdom ───────────────────────
    "caracteres": {
        "title": "Les Caractères",
        "author": "Jean de La Bruyère",
        "gutenberg_id": 17980,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "maximes": {
        "title": "Maximes",
        "author": "La Rochefoucauld",
        "gutenberg_id": 14913,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "reveries-promeneur": {
        "title": "Les Rêveries du promeneur solitaire",
        "author": "Jean-Jacques Rousseau",
        "gutenberg_id": 65434,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "lettres-persanes": {
        "title": "Lettres persanes (Tome I)",
        "author": "Montesquieu",
        "gutenberg_id": 30268,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "esprit-des-lois": {
        "title": "De l'esprit des lois",
        "author": "Montesquieu",
        "gutenberg_id": 27573,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "princesse-cleves": {
        "title": "La Princesse de Clèves",
        "author": "Madame de Lafayette",
        "gutenberg_id": 18797,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "jacques-fataliste": {
        "title": "Jacques le Fataliste et son maître",
        "author": "Denis Diderot",
        "gutenberg_id": 39976,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "neveu-rameau": {
        "title": "Le Neveu de Rameau",
        "author": "Denis Diderot",
        "gutenberg_id": 13862,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "manon-lescaut": {
        "title": "Manon Lescaut",
        "author": "Abbé Prévost",
        "gutenberg_id": 17983,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "colomba": {
        "title": "Colomba",
        "author": "Prosper Mérimée",
        "gutenberg_id": 16239,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "adolphe": {
        "title": "Adolphe",
        "author": "Benjamin Constant",
        "gutenberg_id": 13861,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "zadig": {
        "title": "Zadig, ou la Destinée",
        "author": "Voltaire",
        "gutenberg_id": 4647,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },
    "micromegas": {
        "title": "Micromégas",
        "author": "Voltaire",
        "gutenberg_id": 4649,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Classics (new)",
    },

    # ── More French Literature ──────────────────────────────────────
    "une-vie": {
        "title": "Une Vie",
        "author": "Guy de Maupassant",
        "gutenberg_id": 17457,
        "voice": "Thomas",
        "language": "fr",
        "category": "More French Literature",
    },
    "pierre-et-jean": {
        "title": "Pierre et Jean",
        "author": "Guy de Maupassant",
        "gutenberg_id": 11131,
        "voice": "Thomas",
        "language": "fr",
        "category": "More French Literature",
    },
    "bel-ami": {
        "title": "Bel-Ami",
        "author": "Guy de Maupassant",
        "gutenberg_id": 57430,
        "voice": "Thomas",
        "language": "fr",
        "category": "More French Literature",
    },
}

# Ordered category list for display
BOOK_CATEGORIES = [
    # Philosophy & Wisdom
    "Stoic Philosophy",
    "Greek Philosophy",
    "Eastern Philosophy",
    "Japanese Wisdom",
    "Religious Texts",
    "French Philosophy",
    "German Philosophy",
    "Classical Literature",
    "Roman Wisdom",
    "Persian & Eastern Poetry",
    "Spiritual Classics",
    # French Literature
    "French Literature",
    "French Novels",
    "Jules Verne",
    "French Theatre",
    "French Poetry",
    "French Short Stories",
    "French Philosophy (additional)",
    # Mindfulness & Self-Improvement (new)
    "Mindfulness & Inner Peace",
    "Transcendentalism & Nature",
    "Spiritual Wisdom",
    "Human Condition",
    # French Classics (new)
    "French Classics (new)",
    "More French Literature",
]
