"""50-book audiobook catalog — all French translations, public domain.

Each entry maps a short CLI name to metadata used by stream_tone.py and fetch_books.py.
"""

BOOK_CATALOG = {
    # ── Stoic Philosophy (5) ──────────────────────────────────────────
    "meditations": {
        "title": "Méditations",
        "author": "Marc Aurèle",
        "gutenberg_id": 2680,
        "voice": "Thomas",
        "language": "fr",
        "category": "Stoic Philosophy",
    },
    "enchiridion": {
        "title": "Manuel d'Épictète",
        "author": "Épictète",
        "gutenberg_id": 15476,
        "voice": "Thomas",
        "language": "fr",
        "category": "Stoic Philosophy",
    },
    "lettres-lucilius": {
        "title": "Lettres à Lucilius",
        "author": "Sénèque",
        "gutenberg_id": 56075,
        "voice": "Thomas",
        "language": "fr",
        "category": "Stoic Philosophy",
    },
    "brievete-vie": {
        "title": "De la brièveté de la vie",
        "author": "Sénèque",
        "gutenberg_id": 17941,
        "voice": "Thomas",
        "language": "fr",
        "category": "Stoic Philosophy",
    },
    "tranquillite": {
        "title": "De la tranquillité de l'âme",
        "author": "Sénèque",
        "gutenberg_id": 17942,
        "voice": "Thomas",
        "language": "fr",
        "category": "Stoic Philosophy",
    },

    # ── Greek Philosophy (7) ──────────────────────────────────────────
    "republique": {
        "title": "La République",
        "author": "Platon",
        "gutenberg_id": 14880,
        "voice": "Thomas",
        "language": "fr",
        "category": "Greek Philosophy",
    },
    "apologie": {
        "title": "Apologie de Socrate",
        "author": "Platon",
        "gutenberg_id": 13726,
        "voice": "Thomas",
        "language": "fr",
        "category": "Greek Philosophy",
    },
    "banquet": {
        "title": "Le Banquet",
        "author": "Platon",
        "gutenberg_id": 13789,
        "voice": "Thomas",
        "language": "fr",
        "category": "Greek Philosophy",
    },
    "phedon": {
        "title": "Phédon",
        "author": "Platon",
        "gutenberg_id": 14548,
        "voice": "Thomas",
        "language": "fr",
        "category": "Greek Philosophy",
    },
    "phedre": {
        "title": "Phèdre",
        "author": "Platon",
        "gutenberg_id": 14549,
        "voice": "Thomas",
        "language": "fr",
        "category": "Greek Philosophy",
    },
    "gorgias": {
        "title": "Gorgias",
        "author": "Platon",
        "gutenberg_id": 13790,
        "voice": "Thomas",
        "language": "fr",
        "category": "Greek Philosophy",
    },
    "ethique-nicomaque": {
        "title": "Éthique à Nicomaque",
        "author": "Aristote",
        "gutenberg_id": 43697,
        "voice": "Thomas",
        "language": "fr",
        "category": "Greek Philosophy",
    },

    # ── Eastern Philosophy & Wisdom (5) ───────────────────────────────
    "art-guerre": {
        "title": "L'Art de la guerre",
        "author": "Sun Tzu",
        "gutenberg_id": 17405,
        "voice": "Thomas",
        "language": "fr",
        "category": "Eastern Philosophy",
    },
    "tao-te-king": {
        "title": "Tao Te King",
        "author": "Lao Tseu",
        "gutenberg_id": 14373,
        "voice": "Thomas",
        "language": "fr",
        "category": "Eastern Philosophy",
    },
    "dhammapada": {
        "title": "Dhammapada",
        "author": "Bouddha",
        "gutenberg_id": 12894,
        "voice": "Thomas",
        "language": "fr",
        "category": "Eastern Philosophy",
    },
    "bhagavad-gita": {
        "title": "Bhagavad-Gita",
        "author": "Anonyme",
        "gutenberg_id": 16295,
        "voice": "Thomas",
        "language": "fr",
        "category": "Eastern Philosophy",
    },
    "entretiens-confucius": {
        "title": "Les Entretiens",
        "author": "Confucius",
        "gutenberg_id": 24055,
        "voice": "Thomas",
        "language": "fr",
        "category": "Eastern Philosophy",
    },

    # ── Japanese Wisdom (2) ───────────────────────────────────────────
    "cinq-anneaux": {
        "title": "Le Livre des cinq anneaux",
        "author": "Miyamoto Musashi",
        "gutenberg_id": 50476,
        "voice": "Thomas",
        "language": "fr",
        "category": "Japanese Wisdom",
    },
    "bushido": {
        "title": "Bushido, l'âme du Japon",
        "author": "Inazo Nitobe",
        "gutenberg_id": 12096,
        "voice": "Thomas",
        "language": "fr",
        "category": "Japanese Wisdom",
    },

    # ── Religious Texts (2) ───────────────────────────────────────────
    "bible": {
        "title": "La Sainte Bible (Louis Segond)",
        "author": "Traduction Louis Segond",
        "gutenberg_id": 13029,
        "voice": "Thomas",
        "language": "fr",
        "category": "Religious Texts",
    },
    "coran": {
        "title": "Le Coran",
        "author": "Traduction Kasimirski",
        "gutenberg_id": 7145,
        "voice": "Thomas",
        "language": "fr",
        "category": "Religious Texts",
    },

    # ── French Philosophy (6) ────────────────────────────────────────
    "essais": {
        "title": "Essais",
        "author": "Montaigne",
        "gutenberg_id": 48529,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },
    "discours-methode": {
        "title": "Discours de la méthode",
        "author": "Descartes",
        "gutenberg_id": 13846,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },
    "pensees": {
        "title": "Pensées",
        "author": "Pascal",
        "gutenberg_id": 18269,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },
    "prince": {
        "title": "Le Prince",
        "author": "Machiavel",
        "gutenberg_id": 36513,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },
    "contrat-social": {
        "title": "Du contrat social",
        "author": "Rousseau",
        "gutenberg_id": 15396,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },
    "oracle-manuel": {
        "title": "L'Oracle manuel",
        "author": "Gracián",
        "gutenberg_id": 30865,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },

    # ── German Philosophy in French (3) ──────────────────────────────
    "zarathoustra": {
        "title": "Ainsi parlait Zarathoustra",
        "author": "Nietzsche",
        "gutenberg_id": 44090,
        "voice": "Thomas",
        "language": "fr",
        "category": "German Philosophy",
    },
    "art-raison": {
        "title": "L'Art d'avoir toujours raison",
        "author": "Schopenhauer",
        "gutenberg_id": 52221,
        "voice": "Thomas",
        "language": "fr",
        "category": "German Philosophy",
    },
    "bien-mal": {
        "title": "Par-delà le bien et le mal",
        "author": "Nietzsche",
        "gutenberg_id": 55982,
        "voice": "Thomas",
        "language": "fr",
        "category": "German Philosophy",
    },

    # ── French Literature (8) ────────────────────────────────────────
    "candide": {
        "title": "Candide",
        "author": "Voltaire",
        "gutenberg_id": 4650,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "fables": {
        "title": "Les Fables",
        "author": "La Fontaine",
        "gutenberg_id": 12038,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "fleurs-mal": {
        "title": "Les Fleurs du mal",
        "author": "Baudelaire",
        "gutenberg_id": 6099,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "miserables": {
        "title": "Les Misérables",
        "author": "Victor Hugo",
        "gutenberg_id": 17489,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "monte-cristo": {
        "title": "Le Comte de Monte-Cristo",
        "author": "Alexandre Dumas",
        "gutenberg_id": 17989,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "trois-mousquetaires": {
        "title": "Les Trois Mousquetaires",
        "author": "Alexandre Dumas",
        "gutenberg_id": 13951,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "cyrano": {
        "title": "Cyrano de Bergerac",
        "author": "Edmond Rostand",
        "gutenberg_id": 1256,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "petit-prince": {
        "title": "Le Petit Prince",
        "author": "Antoine de Saint-Exupéry",
        "gutenberg_id": 71370,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },

    # ── Classical Literature (5) ──────────────────────────────────────
    "odyssee": {
        "title": "L'Odyssée",
        "author": "Homère",
        "gutenberg_id": 14868,
        "voice": "Thomas",
        "language": "fr",
        "category": "Classical Literature",
    },
    "iliade": {
        "title": "L'Iliade",
        "author": "Homère",
        "gutenberg_id": 14867,
        "voice": "Thomas",
        "language": "fr",
        "category": "Classical Literature",
    },
    "eneide": {
        "title": "L'Énéide",
        "author": "Virgile",
        "gutenberg_id": 14591,
        "voice": "Thomas",
        "language": "fr",
        "category": "Classical Literature",
    },
    "metamorphoses": {
        "title": "Les Métamorphoses",
        "author": "Ovide",
        "gutenberg_id": 21765,
        "voice": "Thomas",
        "language": "fr",
        "category": "Classical Literature",
    },
    "nature-choses": {
        "title": "De la nature des choses",
        "author": "Lucrèce",
        "gutenberg_id": 18969,
        "voice": "Thomas",
        "language": "fr",
        "category": "Classical Literature",
    },

    # ── Roman Wisdom (2) ─────────────────────────────────────────────
    "amitie": {
        "title": "De l'amitié",
        "author": "Cicéron",
        "gutenberg_id": 16467,
        "voice": "Thomas",
        "language": "fr",
        "category": "Roman Wisdom",
    },
    "vieillesse": {
        "title": "De la vieillesse",
        "author": "Cicéron",
        "gutenberg_id": 16466,
        "voice": "Thomas",
        "language": "fr",
        "category": "Roman Wisdom",
    },

    # ── Persian & Eastern Poetry (2) ──────────────────────────────────
    "rubaiyat": {
        "title": "Les Rubáiyát",
        "author": "Omar Khayyám",
        "gutenberg_id": 21400,
        "voice": "Thomas",
        "language": "fr",
        "category": "Persian & Eastern Poetry",
    },
    "masnavi": {
        "title": "Le Masnavi (extraits)",
        "author": "Rûmî",
        "gutenberg_id": 36131,
        "voice": "Thomas",
        "language": "fr",
        "category": "Persian & Eastern Poetry",
    },

    # ── Spiritual Classics (3) ───────────────────────────────────────
    "ecclesiaste": {
        "title": "L'Ecclésiaste",
        "author": "Salomon",
        "gutenberg_id": 13029,  # Part of Bible (Louis Segond) — extracted section
        "voice": "Thomas",
        "language": "fr",
        "category": "Spiritual Classics",
    },
    "proverbes": {
        "title": "Les Proverbes de Salomon",
        "author": "Salomon",
        "gutenberg_id": 13029,  # Part of Bible (Louis Segond) — extracted section
        "voice": "Thomas",
        "language": "fr",
        "category": "Spiritual Classics",
    },
    "imitation": {
        "title": "L'Imitation de Jésus-Christ",
        "author": "Thomas a Kempis",
        "gutenberg_id": 13090,
        "voice": "Thomas",
        "language": "fr",
        "category": "Spiritual Classics",
    },
}

# Ordered category list for display
BOOK_CATEGORIES = [
    "Stoic Philosophy",
    "Greek Philosophy",
    "Eastern Philosophy",
    "Japanese Wisdom",
    "Religious Texts",
    "French Philosophy",
    "German Philosophy",
    "French Literature",
    "Classical Literature",
    "Roman Wisdom",
    "Persian & Eastern Poetry",
    "Spiritual Classics",
]
