"""Audiobook catalog — 50 English classics + 50 French books, all public domain.

Each entry maps a short CLI name to metadata used by stream_tone.py and fetch_books.py.
Voice is auto-selected by language: Thomas (fr) or Daniel (en).
"""

BOOK_CATALOG = {

    # ══════════════════════════════════════════════════════════════════
    #  ENGLISH CLASSICS (36 EN + 14 FR originals = 50 original books)
    # ══════════════════════════════════════════════════════════════════

    # ── Stoic Philosophy (5) ──────────────────────────────────────────
    "meditations": {
        "title": "Meditations",
        "author": "Marcus Aurelius",
        "gutenberg_id": 2680,
        "voice": "Daniel",
        "language": "en",
        "category": "Stoic Philosophy",
    },
    "enchiridion": {
        "title": "The Enchiridion",
        "author": "Epictetus",
        "gutenberg_id": 45109,
        "voice": "Daniel",
        "language": "en",
        "category": "Stoic Philosophy",
    },
    "lettres-lucilius": {
        "title": "Minor Dialogues (inc. On Shortness of Life)",
        "author": "Seneca",
        "gutenberg_id": 64576,
        "voice": "Daniel",
        "language": "en",
        "category": "Stoic Philosophy",
    },
    "brievete-vie": {
        "title": "Of the Shortness of Life",
        "author": "Seneca",
        "gutenberg_id": 64576,
        "voice": "Daniel",
        "language": "en",
        "category": "Stoic Philosophy",
    },
    "tranquillite": {
        "title": "Of Peace of Mind",
        "author": "Seneca",
        "gutenberg_id": 64576,
        "voice": "Daniel",
        "language": "en",
        "category": "Stoic Philosophy",
    },

    # ── Greek Philosophy (7) ──────────────────────────────────────────
    "republique": {
        "title": "The Republic",
        "author": "Plato",
        "gutenberg_id": 1497,
        "voice": "Daniel",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "apologie": {
        "title": "Apology",
        "author": "Plato",
        "gutenberg_id": 1656,
        "voice": "Daniel",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "banquet": {
        "title": "Symposium",
        "author": "Plato",
        "gutenberg_id": 1600,
        "voice": "Daniel",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "phedon": {
        "title": "Phaedo",
        "author": "Plato",
        "gutenberg_id": 1658,
        "voice": "Daniel",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "phedre": {
        "title": "Phaedrus",
        "author": "Plato",
        "gutenberg_id": 1636,
        "voice": "Daniel",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "gorgias": {
        "title": "Gorgias",
        "author": "Plato",
        "gutenberg_id": 1672,
        "voice": "Daniel",
        "language": "en",
        "category": "Greek Philosophy",
    },
    "ethique-nicomaque": {
        "title": "Nicomachean Ethics",
        "author": "Aristotle",
        "gutenberg_id": 8438,
        "voice": "Daniel",
        "language": "en",
        "category": "Greek Philosophy",
    },

    # ── Eastern Philosophy & Wisdom (5) ───────────────────────────────
    "art-guerre": {
        "title": "The Art of War",
        "author": "Sun Tzu",
        "gutenberg_id": 132,
        "voice": "Daniel",
        "language": "en",
        "category": "Eastern Philosophy",
    },
    "tao-te-king": {
        "title": "Tao Te Ching",
        "author": "Lao Tzu",
        "gutenberg_id": 216,
        "voice": "Daniel",
        "language": "en",
        "category": "Eastern Philosophy",
    },
    "dhammapada": {
        "title": "Dhammapada",
        "author": "Buddha",
        "gutenberg_id": 2017,
        "voice": "Daniel",
        "language": "en",
        "category": "Eastern Philosophy",
    },
    "bhagavad-gita": {
        "title": "Bhagavad-Gita",
        "author": "Vyasa",
        "gutenberg_id": 2388,
        "voice": "Daniel",
        "language": "en",
        "category": "Eastern Philosophy",
    },
    "entretiens-confucius": {
        "title": "Les quatre livres de philosophie",
        "author": "Confucius",
        "gutenberg_id": 44958,
        "voice": "Thomas",
        "language": "fr",
        "category": "Eastern Philosophy",
    },

    # ── Japanese Wisdom (2) ───────────────────────────────────────────
    "cinq-anneaux": {
        "title": "Bushido, the Soul of Japan",
        "author": "Inazo Nitobe",
        "gutenberg_id": 12096,
        "voice": "Daniel",
        "language": "en",
        "category": "Japanese Wisdom",
    },
    "bushido": {
        "title": "Bushido, the Soul of Japan",
        "author": "Inazo Nitobe",
        "gutenberg_id": 12096,
        "voice": "Daniel",
        "language": "en",
        "category": "Japanese Wisdom",
    },

    # ── Religious Texts (2) ───────────────────────────────────────────
    "bible": {
        "title": "The Bible (King James Version)",
        "author": "King James",
        "gutenberg_id": 10,
        "voice": "Daniel",
        "language": "en",
        "category": "Religious Texts",
    },
    "coran": {
        "title": "The Quran",
        "author": "tr. Rodwell",
        "gutenberg_id": 2800,
        "voice": "Daniel",
        "language": "en",
        "category": "Religious Texts",
    },

    # ── French Philosophy (6) — originals in French! ─────────────────
    "essais": {
        "title": "Essais",
        "author": "Montaigne",
        "gutenberg_id": 48529,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },
    "discours-methode": {
        "title": "Discours de la méthode",
        "author": "Descartes",
        "gutenberg_id": 13846,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy",
    },
    "pensees": {
        "title": "Pensées",
        "author": "Pascal",
        "gutenberg_id": 46921,
        "voice": "Daniel",
        "language": "en",
        "category": "French Philosophy",
    },
    "prince": {
        "title": "The Prince",
        "author": "Machiavelli",
        "gutenberg_id": 1232,
        "voice": "Daniel",
        "language": "en",
        "category": "French Philosophy",
    },
    "contrat-social": {
        "title": "The Social Contract",
        "author": "Rousseau",
        "gutenberg_id": 46333,
        "voice": "Daniel",
        "language": "en",
        "category": "French Philosophy",
    },
    "oracle-manuel": {
        "title": "The Art of Controversy",
        "author": "Schopenhauer",
        "gutenberg_id": 10731,
        "voice": "Daniel",
        "language": "en",
        "category": "French Philosophy",
    },

    # ── German Philosophy in French (3) ──────────────────────────────
    "zarathoustra": {
        "title": "Ainsi parlait Zarathoustra",
        "author": "Nietzsche",
        "gutenberg_id": 5258,
        "voice": "Thomas",
        "language": "fr",
        "category": "German Philosophy",
    },
    "art-raison": {
        "title": "The Art of Controversy",
        "author": "Schopenhauer",
        "gutenberg_id": 10731,
        "voice": "Daniel",
        "language": "en",
        "category": "German Philosophy",
    },
    "bien-mal": {
        "title": "Beyond Good and Evil",
        "author": "Nietzsche",
        "gutenberg_id": 4363,
        "voice": "Daniel",
        "language": "en",
        "category": "German Philosophy",
    },

    # ── French Literature (8) — originals in French! ─────────────────
    "candide": {
        "title": "Candide",
        "author": "Voltaire",
        "gutenberg_id": 4650,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "fables": {
        "title": "Les Fables",
        "author": "La Fontaine",
        "gutenberg_id": 56327,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "fleurs-mal": {
        "title": "Les Fleurs du mal",
        "author": "Baudelaire",
        "gutenberg_id": 6099,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "miserables": {
        "title": "Les Misérables",
        "author": "Victor Hugo",
        "gutenberg_id": 17489,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "monte-cristo": {
        "title": "Le Comte de Monte-Cristo",
        "author": "Alexandre Dumas",
        "gutenberg_id": 17989,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "trois-mousquetaires": {
        "title": "Les Trois Mousquetaires",
        "author": "Alexandre Dumas",
        "gutenberg_id": 13951,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "cyrano": {
        "title": "Cyrano de Bergerac",
        "author": "Edmond Rostand",
        "gutenberg_id": 1256,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Literature",
    },
    "petit-prince": {
        "title": "Rubaiyat of Omar Khayyam",
        "author": "Omar Khayyam",
        "gutenberg_id": 246,
        "voice": "Daniel",
        "language": "en",
        "category": "French Literature",
    },

    # ── Classical Literature (5) ──────────────────────────────────────
    "odyssee": {
        "title": "L'Odyssée",
        "author": "Homère",
        "gutenberg_id": 14286,
        "voice": "Thomas",
        "language": "fr",
        "category": "Classical Literature",
    },
    "iliade": {
        "title": "L'Iliade",
        "author": "Homère",
        "gutenberg_id": 14285,
        "voice": "Thomas",
        "language": "fr",
        "category": "Classical Literature",
    },
    "eneide": {
        "title": "The Aeneid",
        "author": "Virgil",
        "gutenberg_id": 228,
        "voice": "Daniel",
        "language": "en",
        "category": "Classical Literature",
    },
    "metamorphoses": {
        "title": "The Metamorphoses",
        "author": "Ovid",
        "gutenberg_id": 21765,
        "voice": "Daniel",
        "language": "en",
        "category": "Classical Literature",
    },
    "nature-choses": {
        "title": "On the Nature of Things",
        "author": "Lucretius",
        "gutenberg_id": 785,
        "voice": "Daniel",
        "language": "en",
        "category": "Classical Literature",
    },

    # ── Roman Wisdom (2) ─────────────────────────────────────────────
    "amitie": {
        "title": "Treatises on Friendship and Old Age",
        "author": "Cicero",
        "gutenberg_id": 2808,
        "voice": "Daniel",
        "language": "en",
        "category": "Roman Wisdom",
    },
    "vieillesse": {
        "title": "Treatises on Friendship and Old Age",
        "author": "Cicero",
        "gutenberg_id": 2808,
        "voice": "Daniel",
        "language": "en",
        "category": "Roman Wisdom",
    },

    # ── Persian & Eastern Poetry (2) ──────────────────────────────────
    "rubaiyat": {
        "title": "Rubaiyat of Omar Khayyam",
        "author": "Omar Khayyam",
        "gutenberg_id": 246,
        "voice": "Daniel",
        "language": "en",
        "category": "Persian & Eastern Poetry",
    },
    "masnavi": {
        "title": "L'Imitation de Jésus-Christ",
        "author": "Thomas a Kempis",
        "gutenberg_id": 57824,
        "voice": "Thomas",
        "language": "fr",
        "category": "Persian & Eastern Poetry",
    },

    # ── Spiritual Classics (3) ───────────────────────────────────────
    "ecclesiaste": {
        "title": "The Bible (King James Version)",
        "author": "King James",
        "gutenberg_id": 10,
        "voice": "Daniel",
        "language": "en",
        "category": "Spiritual Classics",
    },
    "proverbes": {
        "title": "The Bible (King James Version)",
        "author": "King James",
        "gutenberg_id": 10,
        "voice": "Daniel",
        "language": "en",
        "category": "Spiritual Classics",
    },
    "imitation": {
        "title": "L'Imitation de Jésus-Christ",
        "author": "Thomas a Kempis",
        "gutenberg_id": 57824,
        "voice": "Thomas",
        "language": "fr",
        "category": "Spiritual Classics",
    },

    # ══════════════════════════════════════════════════════════════════
    #  FRENCH LITERATURE — 36 verified French books from Gutenberg
    # ══════════════════════════════════════════════════════════════════

    # ── French Novels ────────────────────────────────────────────────
    "madame-bovary": {
        "title": "Madame Bovary",
        "author": "Gustave Flaubert",
        "gutenberg_id": 14155,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "rouge-et-noir": {
        "title": "Le rouge et le noir",
        "author": "Stendhal",
        "gutenberg_id": 798,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "chartreuse-de-parme": {
        "title": "La Chartreuse de Parme",
        "author": "Stendhal",
        "gutenberg_id": 796,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "eugenie-grandet": {
        "title": "Eugénie Grandet",
        "author": "Honoré de Balzac",
        "gutenberg_id": 11049,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "germinal": {
        "title": "Germinal",
        "author": "Émile Zola",
        "gutenberg_id": 5711,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "nana": {
        "title": "Nana",
        "author": "Émile Zola",
        "gutenberg_id": 5250,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "assommoir": {
        "title": "L'Assommoir",
        "author": "Émile Zola",
        "gutenberg_id": 6497,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "therese-raquin": {
        "title": "Thérèse Raquin",
        "author": "Émile Zola",
        "gutenberg_id": 7461,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "notre-dame-de-paris": {
        "title": "Notre-Dame de Paris",
        "author": "Victor Hugo",
        "gutenberg_id": 19657,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "homme-qui-rit": {
        "title": "L'homme qui rit",
        "author": "Victor Hugo",
        "gutenberg_id": 5423,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "quatrevingt-treize": {
        "title": "Quatrevingt-Treize",
        "author": "Victor Hugo",
        "gutenberg_id": 9645,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "dame-aux-camelias": {
        "title": "La dame aux camélias",
        "author": "Alexandre Dumas fils",
        "gutenberg_id": 2419,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "liaisons-dangereuses": {
        "title": "Les liaisons dangereuses",
        "author": "Choderlos de Laclos",
        "gutenberg_id": 52006,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "grand-meaulnes": {
        "title": "Le Grand Meaulnes",
        "author": "Alain-Fournier",
        "gutenberg_id": 5781,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "fantome-opera": {
        "title": "Le Fantôme de l'Opéra",
        "author": "Gaston Leroux",
        "gutenberg_id": 62215,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "arsene-lupin": {
        "title": "Arsène Lupin, gentleman-cambrioleur",
        "author": "Maurice Leblanc",
        "gutenberg_id": 32854,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "petite-fadette": {
        "title": "La petite Fadette",
        "author": "George Sand",
        "gutenberg_id": 34204,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "a-rebours": {
        "title": "À rebours",
        "author": "J.-K. Huysmans",
        "gutenberg_id": 56149,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },
    "du-cote-de-chez-swann": {
        "title": "Du côté de chez Swann",
        "author": "Marcel Proust",
        "gutenberg_id": 2650,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Novels",
    },

    # ── Jules Verne ──────────────────────────────────────────────────
    "tour-du-monde": {
        "title": "Le tour du monde en quatre-vingts jours",
        "author": "Jules Verne",
        "gutenberg_id": 20973,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },
    "voyage-centre-terre": {
        "title": "Voyage au centre de la Terre",
        "author": "Jules Verne",
        "gutenberg_id": 4791,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },
    "vingt-mille-lieues": {
        "title": "Vingt mille lieues sous les mers",
        "author": "Jules Verne",
        "gutenberg_id": 5097,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },
    "ile-mysterieuse": {
        "title": "L'île mystérieuse",
        "author": "Jules Verne",
        "gutenberg_id": 14287,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },
    "de-la-terre-a-la-lune": {
        "title": "De la terre à la lune",
        "author": "Jules Verne",
        "gutenberg_id": 38674,
        "voice": "Thomas",
        "language": "fr",
        "category": "Jules Verne",
    },

    # ── French Theatre ───────────────────────────────────────────────
    "avare": {
        "title": "L'Avare",
        "author": "Molière",
        "gutenberg_id": 6318,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Theatre",
    },
    "don-juan": {
        "title": "Don Juan, ou le Festin de pierre",
        "author": "Molière",
        "gutenberg_id": 5130,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Theatre",
    },
    "hernani": {
        "title": "Hernani",
        "author": "Victor Hugo",
        "gutenberg_id": 9976,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Theatre",
    },

    # ── French Poetry ────────────────────────────────────────────────
    "alcools": {
        "title": "Alcools",
        "author": "Guillaume Apollinaire",
        "gutenberg_id": 15462,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Poetry",
    },
    "poesies-rimbaud": {
        "title": "Poésies complètes",
        "author": "Arthur Rimbaud",
        "gutenberg_id": 29302,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Poetry",
    },
    "verlaine-oeuvres": {
        "title": "Œuvres complètes, Volume 1",
        "author": "Paul Verlaine",
        "gutenberg_id": 15112,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Poetry",
    },
    "legende-des-siecles": {
        "title": "La Légende des siècles",
        "author": "Victor Hugo",
        "gutenberg_id": 12137,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Poetry",
    },

    # ── French Short Stories ─────────────────────────────────────────
    "boule-de-suif": {
        "title": "Boule de Suif",
        "author": "Guy de Maupassant",
        "gutenberg_id": 10746,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Short Stories",
    },
    "le-horla": {
        "title": "Le Horla",
        "author": "Guy de Maupassant",
        "gutenberg_id": 10775,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Short Stories",
    },
    "contes-de-perrault": {
        "title": "Histoires ou Contes du temps passé",
        "author": "Charles Perrault",
        "gutenberg_id": 20972,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Short Stories",
    },
    "lettres-de-mon-moulin": {
        "title": "Lettres de mon moulin",
        "author": "Alphonse Daudet",
        "gutenberg_id": 36780,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Short Stories",
    },

    # ── French Philosophy (additional) ───────────────────────────────
    "traite-tolerance": {
        "title": "Traité sur la tolérance",
        "author": "Voltaire",
        "gutenberg_id": 42131,
        "voice": "Thomas",
        "language": "fr",
        "category": "French Philosophy (additional)",
    },
}

# Ordered category list for display
BOOK_CATEGORIES = [
    # Original 50
    "Stoic Philosophy",
    "Greek Philosophy",
    "Eastern Philosophy",
    "Japanese Wisdom",
    "Religious Texts",
    "French Philosophy",
    "German Philosophy",
    "French Literature",
    "Classical Literature",
    "Roman Wisdom",
    "Persian & Eastern Poetry",
    "Spiritual Classics",
    # 36 new French books
    "French Novels",
    "Jules Verne",
    "French Theatre",
    "French Poetry",
    "French Short Stories",
    "French Philosophy (additional)",
]
