"""
New audiobook catalog entries — ~210 English books
(Philosophy, Personal Improvement, English Classics / Literature)

Ready to paste into BOOK_CATALOG in books/catalog.py.
All Gutenberg IDs verified against gutenberg.org.
"""

NEW_ENTRIES = {

    # ══════════════════════════════════════════════════════════════════
    #  PHILOSOPHY (~60 books)
    # ══════════════════════════════════════════════════════════════════

    # ── Kant (5) ────────────────────────────────────────────────────
    "critique-pure-reason": {
        "title": "The Critique of Pure Reason",
        "author": "Immanuel Kant",
        "gutenberg_id": 4280,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "critique-practical-reason": {
        "title": "The Critique of Practical Reason",
        "author": "Immanuel Kant",
        "gutenberg_id": 5683,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "critique-judgement": {
        "title": "Kant's Critique of Judgement",
        "author": "Immanuel Kant",
        "gutenberg_id": 48433,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "metaphysic-morals": {
        "title": "Fundamental Principles of the Metaphysic of Morals",
        "author": "Immanuel Kant",
        "gutenberg_id": 5682,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "kant-prolegomena": {
        "title": "Prolegomena to Any Future Metaphysics",
        "author": "Immanuel Kant",
        "gutenberg_id": 52821,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Hegel (5) ───────────────────────────────────────────────────
    "hegel-logic": {
        "title": "The Logic of Hegel",
        "author": "Georg Wilhelm Friedrich Hegel",
        "gutenberg_id": 55108,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "hegel-philosophy-mind": {
        "title": "Hegel's Philosophy of Mind",
        "author": "Georg Wilhelm Friedrich Hegel",
        "gutenberg_id": 39064,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "hegel-history-philosophy-1": {
        "title": "Lectures on the History of Philosophy, Vol. 1",
        "author": "Georg Wilhelm Friedrich Hegel",
        "gutenberg_id": 51635,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
        "series": "Hegel's History of Philosophy",
        "series_order": 1,
    },
    "hegel-history-philosophy-2": {
        "title": "Lectures on the History of Philosophy, Vol. 2",
        "author": "Georg Wilhelm Friedrich Hegel",
        "gutenberg_id": 51636,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
        "series": "Hegel's History of Philosophy",
        "series_order": 2,
    },
    "hegel-history-philosophy-3": {
        "title": "Lectures on the History of Philosophy, Vol. 3",
        "author": "Georg Wilhelm Friedrich Hegel",
        "gutenberg_id": 58169,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
        "series": "Hegel's History of Philosophy",
        "series_order": 3,
    },

    # ── Schopenhauer (6) ────────────────────────────────────────────
    "world-will-idea-1": {
        "title": "The World as Will and Idea, Vol. 1",
        "author": "Arthur Schopenhauer",
        "gutenberg_id": 38427,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
        "series": "The World as Will and Idea",
        "series_order": 1,
    },
    "world-will-idea-2": {
        "title": "The World as Will and Idea, Vol. 2",
        "author": "Arthur Schopenhauer",
        "gutenberg_id": 40097,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
        "series": "The World as Will and Idea",
        "series_order": 2,
    },
    "world-will-idea-3": {
        "title": "The World as Will and Idea, Vol. 3",
        "author": "Arthur Schopenhauer",
        "gutenberg_id": 40868,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
        "series": "The World as Will and Idea",
        "series_order": 3,
    },
    "wisdom-of-life": {
        "title": "The Wisdom of Life",
        "author": "Arthur Schopenhauer",
        "gutenberg_id": 10741,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "studies-pessimism": {
        "title": "Studies in Pessimism",
        "author": "Arthur Schopenhauer",
        "gutenberg_id": 10732,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "basis-of-morality": {
        "title": "The Basis of Morality",
        "author": "Arthur Schopenhauer",
        "gutenberg_id": 44929,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── John Stuart Mill (4) ────────────────────────────────────────
    "on-liberty": {
        "title": "On Liberty",
        "author": "John Stuart Mill",
        "gutenberg_id": 34901,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "utilitarianism": {
        "title": "Utilitarianism",
        "author": "John Stuart Mill",
        "gutenberg_id": 11224,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "subjection-of-women": {
        "title": "The Subjection of Women",
        "author": "John Stuart Mill",
        "gutenberg_id": 27083,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "mill-autobiography": {
        "title": "Autobiography",
        "author": "John Stuart Mill",
        "gutenberg_id": 10378,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── David Hume (4) ──────────────────────────────────────────────
    "enquiry-human-understanding": {
        "title": "An Enquiry Concerning Human Understanding",
        "author": "David Hume",
        "gutenberg_id": 9662,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "treatise-human-nature": {
        "title": "A Treatise of Human Nature",
        "author": "David Hume",
        "gutenberg_id": 4705,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "enquiry-principles-morals": {
        "title": "An Enquiry Concerning the Principles of Morals",
        "author": "David Hume",
        "gutenberg_id": 4320,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "dialogues-natural-religion": {
        "title": "Dialogues Concerning Natural Religion",
        "author": "David Hume",
        "gutenberg_id": 4583,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── John Locke (2) ──────────────────────────────────────────────
    "second-treatise-government": {
        "title": "Second Treatise of Government",
        "author": "John Locke",
        "gutenberg_id": 7370,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "essay-human-understanding-1": {
        "title": "An Essay Concerning Humane Understanding, Vol. 1",
        "author": "John Locke",
        "gutenberg_id": 10615,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
        "series": "Essay Concerning Human Understanding",
        "series_order": 1,
    },

    # ── Thomas Hobbes (1) ───────────────────────────────────────────
    "leviathan": {
        "title": "Leviathan",
        "author": "Thomas Hobbes",
        "gutenberg_id": 3207,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Bertrand Russell (5) ────────────────────────────────────────
    "conquest-of-happiness": {
        "title": "The Conquest of Happiness",
        "author": "Bertrand Russell",
        "gutenberg_id": 77894,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "analysis-of-mind": {
        "title": "The Analysis of Mind",
        "author": "Bertrand Russell",
        "gutenberg_id": 2529,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "mysticism-and-logic": {
        "title": "Mysticism and Logic and Other Essays",
        "author": "Bertrand Russell",
        "gutenberg_id": 25447,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "proposed-roads-freedom": {
        "title": "Proposed Roads to Freedom",
        "author": "Bertrand Russell",
        "gutenberg_id": 690,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "political-ideals-russell": {
        "title": "Political Ideals",
        "author": "Bertrand Russell",
        "gutenberg_id": 4776,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Francis Bacon (2) ───────────────────────────────────────────
    "essays-bacon": {
        "title": "The Essays or Counsels, Civil and Moral",
        "author": "Francis Bacon",
        "gutenberg_id": 575,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "advancement-of-learning": {
        "title": "The Advancement of Learning",
        "author": "Francis Bacon",
        "gutenberg_id": 5500,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Descartes (EN) (2) ──────────────────────────────────────────
    "discourse-method-en": {
        "title": "Discourse on the Method",
        "author": "René Descartes",
        "gutenberg_id": 59,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "meditations-descartes": {
        "title": "Six Metaphysical Meditations",
        "author": "René Descartes",
        "gutenberg_id": 70091,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Spinoza (1) ─────────────────────────────────────────────────
    "ethics-spinoza": {
        "title": "Ethics",
        "author": "Benedictus de Spinoza",
        "gutenberg_id": 3800,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Leibniz (1) ─────────────────────────────────────────────────
    "theodicy": {
        "title": "Theodicy",
        "author": "Gottfried Wilhelm Leibniz",
        "gutenberg_id": 17147,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Berkeley (1) ────────────────────────────────────────────────
    "principles-human-knowledge": {
        "title": "A Treatise Concerning the Principles of Human Knowledge",
        "author": "George Berkeley",
        "gutenberg_id": 4723,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Thomas Paine (3) ────────────────────────────────────────────
    "common-sense": {
        "title": "Common Sense",
        "author": "Thomas Paine",
        "gutenberg_id": 147,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "rights-of-man": {
        "title": "The Rights of Man",
        "author": "Thomas Paine",
        "gutenberg_id": 3742,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "age-of-reason": {
        "title": "The Age of Reason",
        "author": "Thomas Paine",
        "gutenberg_id": 3743,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Voltaire (EN) (3) ───────────────────────────────────────────
    "letters-on-england": {
        "title": "Letters on England",
        "author": "Voltaire",
        "gutenberg_id": 2445,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "philosophical-dictionary": {
        "title": "Voltaire's Philosophical Dictionary",
        "author": "Voltaire",
        "gutenberg_id": 18569,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "toleration-essays": {
        "title": "Toleration and Other Essays",
        "author": "Voltaire",
        "gutenberg_id": 64858,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Rousseau (EN) (3) ───────────────────────────────────────────
    "confessions-rousseau": {
        "title": "The Confessions of Jean Jacques Rousseau",
        "author": "Jean-Jacques Rousseau",
        "gutenberg_id": 3913,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "emile": {
        "title": "Emile; or, On Education",
        "author": "Jean-Jacques Rousseau",
        "gutenberg_id": 5427,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "discourse-inequality": {
        "title": "A Discourse Upon the Origin of Inequality",
        "author": "Jean-Jacques Rousseau",
        "gutenberg_id": 11136,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Nietzsche (EN, beyond Zarathustra & Beyond Good and Evil) (7)
    "thus-spake-zarathustra": {
        "title": "Thus Spake Zarathustra",
        "author": "Friedrich Nietzsche",
        "gutenberg_id": 1998,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "genealogy-of-morals": {
        "title": "The Genealogy of Morals",
        "author": "Friedrich Nietzsche",
        "gutenberg_id": 52319,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "twilight-of-idols": {
        "title": "The Twilight of the Idols / The Antichrist",
        "author": "Friedrich Nietzsche",
        "gutenberg_id": 52263,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "birth-of-tragedy": {
        "title": "The Birth of Tragedy",
        "author": "Friedrich Nietzsche",
        "gutenberg_id": 51356,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "human-all-too-human": {
        "title": "Human, All Too Human",
        "author": "Friedrich Nietzsche",
        "gutenberg_id": 38145,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "joyful-wisdom": {
        "title": "The Joyful Wisdom (La Gaya Scienza)",
        "author": "Friedrich Nietzsche",
        "gutenberg_id": 52881,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "dawn-of-day": {
        "title": "The Dawn of Day",
        "author": "Friedrich Nietzsche",
        "gutenberg_id": 39955,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Kierkegaard (1) ─────────────────────────────────────────────
    "kierkegaard-selections": {
        "title": "Selections from the Writings of Kierkegaard",
        "author": "Søren Kierkegaard",
        "gutenberg_id": 60333,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Henri Bergson (3) ───────────────────────────────────────────
    "creative-evolution": {
        "title": "Creative Evolution",
        "author": "Henri Bergson",
        "gutenberg_id": 26163,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "time-and-free-will": {
        "title": "Time and Free Will",
        "author": "Henri Bergson",
        "gutenberg_id": 56852,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "laughter-bergson": {
        "title": "Laughter: An Essay on the Meaning of the Comic",
        "author": "Henri Bergson",
        "gutenberg_id": 4352,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ── Other Philosophy (3) ────────────────────────────────────────
    "origin-of-species": {
        "title": "On the Origin of Species",
        "author": "Charles Darwin",
        "gutenberg_id": 1228,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "the-law-bastiat": {
        "title": "The Law",
        "author": "Frédéric Bastiat",
        "gutenberg_id": 44800,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },
    "perpetual-peace": {
        "title": "Perpetual Peace: A Philosophical Essay",
        "author": "Immanuel Kant",
        "gutenberg_id": 50922,
        "voice": "Samantha",
        "language": "en",
        "category": "Philosophy",
    },

    # ══════════════════════════════════════════════════════════════════
    #  PERSONAL IMPROVEMENT / SELF-HELP (~50 books)
    # ══════════════════════════════════════════════════════════════════

    # ── Benjamin Franklin (1) ───────────────────────────────────────
    "autobiography-franklin": {
        "title": "The Autobiography of Benjamin Franklin",
        "author": "Benjamin Franklin",
        "gutenberg_id": 20203,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Samuel Smiles (2 — 935 already in catalog) ──────────────────
    "character-smiles": {
        "title": "Character",
        "author": "Samuel Smiles",
        "gutenberg_id": 2541,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "thrift-smiles": {
        "title": "Thrift",
        "author": "Samuel Smiles",
        "gutenberg_id": 14418,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Orison Swett Marden (8) ─────────────────────────────────────
    "pushing-to-the-front": {
        "title": "Pushing to the Front",
        "author": "Orison Swett Marden",
        "gutenberg_id": 21291,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "architects-of-fate": {
        "title": "Architects of Fate; Or, Steps to Success and Power",
        "author": "Orison Swett Marden",
        "gutenberg_id": 21622,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "how-to-succeed": {
        "title": "How to Succeed; Or, Stepping-Stones to Fame and Fortune",
        "author": "Orison Swett Marden",
        "gutenberg_id": 20513,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "victorious-attitude": {
        "title": "The Victorious Attitude",
        "author": "Orison Swett Marden",
        "gutenberg_id": 41901,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "iron-will": {
        "title": "An Iron Will",
        "author": "Orison Swett Marden",
        "gutenberg_id": 13160,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "cheerfulness-life-power": {
        "title": "Cheerfulness as a Life Power",
        "author": "Orison Swett Marden",
        "gutenberg_id": 18394,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "ambition-and-success": {
        "title": "Ambition and Success",
        "author": "Orison Swett Marden",
        "gutenberg_id": 57651,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "how-they-succeeded": {
        "title": "How They Succeeded",
        "author": "Orison Swett Marden",
        "gutenberg_id": 64059,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── William Walker Atkinson (additional, beyond already-included)
    "art-logical-thinking": {
        "title": "The Art of Logical Thinking",
        "author": "William Walker Atkinson",
        "gutenberg_id": 41838,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "mind-and-body": {
        "title": "Mind and Body; or, Mental States and Physical Conditions",
        "author": "William Walker Atkinson",
        "gutenberg_id": 44029,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "psychology-salesmanship": {
        "title": "The Psychology of Salesmanship",
        "author": "William Walker Atkinson",
        "gutenberg_id": 41510,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "how-to-read-human-nature": {
        "title": "How to Read Human Nature",
        "author": "William Walker Atkinson",
        "gutenberg_id": 41501,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "nuggets-new-thought": {
        "title": "Nuggets of the New Thought",
        "author": "William Walker Atkinson",
        "gutenberg_id": 45113,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "practical-mind-reading": {
        "title": "Practical Mind-Reading",
        "author": "William Walker Atkinson",
        "gutenberg_id": 41358,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "reincarnation-karma": {
        "title": "Reincarnation and the Law of Karma",
        "author": "William Walker Atkinson",
        "gutenberg_id": 26364,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Florence Scovel Shinn (1) ───────────────────────────────────
    "game-of-life": {
        "title": "The Game of Life and How to Play It",
        "author": "Florence Scovel Shinn",
        "gutenberg_id": 74878,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Ralph Waldo Trine (3) ───────────────────────────────────────
    "in-tune-infinite": {
        "title": "In Tune with the Infinite",
        "author": "Ralph Waldo Trine",
        "gutenberg_id": 23559,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "higher-powers-mind": {
        "title": "The Higher Powers of Mind and Spirit",
        "author": "Ralph Waldo Trine",
        "gutenberg_id": 28163,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "what-all-world-seeking": {
        "title": "What All the World's A-Seeking",
        "author": "Ralph Waldo Trine",
        "gutenberg_id": 14312,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── P.T. Barnum (2) ────────────────────────────────────────────
    "art-money-getting": {
        "title": "The Art of Money Getting",
        "author": "P. T. Barnum",
        "gutenberg_id": 8581,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "struggles-triumphs": {
        "title": "Struggles and Triumphs",
        "author": "P. T. Barnum",
        "gutenberg_id": 50115,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Russell Conwell (1) ─────────────────────────────────────────
    "acres-of-diamonds": {
        "title": "Acres of Diamonds",
        "author": "Russell H. Conwell",
        "gutenberg_id": 368,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Horatio Alger (2) ───────────────────────────────────────────
    "ragged-dick": {
        "title": "Ragged Dick",
        "author": "Horatio Alger Jr.",
        "gutenberg_id": 5348,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "struggling-upward": {
        "title": "Struggling Upward, or Luke Larkin's Luck",
        "author": "Horatio Alger Jr.",
        "gutenberg_id": 5417,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Henry Drummond (1) ──────────────────────────────────────────
    "greatest-thing-world": {
        "title": "The Greatest Thing in the World",
        "author": "Henry Drummond",
        "gutenberg_id": 16739,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Andrew Carnegie (2) ─────────────────────────────────────────
    "gospel-of-wealth": {
        "title": "The Gospel of Wealth",
        "author": "Andrew Carnegie",
        "gutenberg_id": 10253,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "autobiography-carnegie": {
        "title": "Autobiography of Andrew Carnegie",
        "author": "Andrew Carnegie",
        "gutenberg_id": 17976,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Elbert Hubbard (1) ──────────────────────────────────────────
    "message-to-garcia": {
        "title": "A Message to Garcia",
        "author": "Elbert Hubbard",
        "gutenberg_id": 17195,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },

    # ── Tolstoy — Self-Help/Spiritual (3) ──────────────────────────
    "kingdom-god-within": {
        "title": "The Kingdom of God Is Within You",
        "author": "Leo Tolstoy",
        "gutenberg_id": 4602,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "what-is-art": {
        "title": "What Is Art?",
        "author": "Leo Tolstoy",
        "gutenberg_id": 64908,
        "voice": "Samantha",
        "language": "en",
        "category": "Personal Improvement",
    },
    "kreutzer-sonata": {
        "title": "The Kreutzer Sonata and Other Stories",
        "author": "Leo Tolstoy",
        "gutenberg_id": 689,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ══════════════════════════════════════════════════════════════════
    #  ENGLISH CLASSICS / LITERATURE (~100 books)
    # ══════════════════════════════════════════════════════════════════

    # ── Shakespeare (14) ────────────────────────────────────────────
    "hamlet": {
        "title": "Hamlet",
        "author": "William Shakespeare",
        "gutenberg_id": 1524,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "macbeth": {
        "title": "Macbeth",
        "author": "William Shakespeare",
        "gutenberg_id": 1533,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "othello": {
        "title": "Othello",
        "author": "William Shakespeare",
        "gutenberg_id": 1531,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "king-lear": {
        "title": "King Lear",
        "author": "William Shakespeare",
        "gutenberg_id": 1532,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "romeo-and-juliet": {
        "title": "Romeo and Juliet",
        "author": "William Shakespeare",
        "gutenberg_id": 1513,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "midsummer-nights-dream": {
        "title": "A Midsummer Night's Dream",
        "author": "William Shakespeare",
        "gutenberg_id": 1514,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "tempest": {
        "title": "The Tempest",
        "author": "William Shakespeare",
        "gutenberg_id": 23042,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "merchant-of-venice": {
        "title": "The Merchant of Venice",
        "author": "William Shakespeare",
        "gutenberg_id": 1515,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "much-ado-nothing": {
        "title": "Much Ado About Nothing",
        "author": "William Shakespeare",
        "gutenberg_id": 1519,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "twelfth-night": {
        "title": "Twelfth Night",
        "author": "William Shakespeare",
        "gutenberg_id": 1526,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "julius-caesar": {
        "title": "Julius Caesar",
        "author": "William Shakespeare",
        "gutenberg_id": 1522,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "as-you-like-it": {
        "title": "As You Like It",
        "author": "William Shakespeare",
        "gutenberg_id": 1523,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "taming-of-shrew": {
        "title": "The Taming of the Shrew",
        "author": "William Shakespeare",
        "gutenberg_id": 2245,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "henry-v": {
        "title": "King Henry V",
        "author": "William Shakespeare",
        "gutenberg_id": 2253,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Jane Austen (6) ────────────────────────────────────────────
    "pride-and-prejudice": {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "gutenberg_id": 1342,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "sense-and-sensibility": {
        "title": "Sense and Sensibility",
        "author": "Jane Austen",
        "gutenberg_id": 161,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "emma": {
        "title": "Emma",
        "author": "Jane Austen",
        "gutenberg_id": 158,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "mansfield-park": {
        "title": "Mansfield Park",
        "author": "Jane Austen",
        "gutenberg_id": 141,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "northanger-abbey": {
        "title": "Northanger Abbey",
        "author": "Jane Austen",
        "gutenberg_id": 121,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "persuasion": {
        "title": "Persuasion",
        "author": "Jane Austen",
        "gutenberg_id": 105,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Charles Dickens (10, Tale of Two Cities already in catalog) ─
    "great-expectations": {
        "title": "Great Expectations",
        "author": "Charles Dickens",
        "gutenberg_id": 1400,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "oliver-twist": {
        "title": "Oliver Twist",
        "author": "Charles Dickens",
        "gutenberg_id": 730,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "david-copperfield": {
        "title": "David Copperfield",
        "author": "Charles Dickens",
        "gutenberg_id": 766,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "bleak-house": {
        "title": "Bleak House",
        "author": "Charles Dickens",
        "gutenberg_id": 1023,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "christmas-carol": {
        "title": "A Christmas Carol",
        "author": "Charles Dickens",
        "gutenberg_id": 46,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "nicholas-nickleby": {
        "title": "Nicholas Nickleby",
        "author": "Charles Dickens",
        "gutenberg_id": 967,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "little-dorrit": {
        "title": "Little Dorrit",
        "author": "Charles Dickens",
        "gutenberg_id": 963,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "our-mutual-friend": {
        "title": "Our Mutual Friend",
        "author": "Charles Dickens",
        "gutenberg_id": 883,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "pickwick-papers": {
        "title": "The Pickwick Papers",
        "author": "Charles Dickens",
        "gutenberg_id": 580,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "hard-times": {
        "title": "Hard Times",
        "author": "Charles Dickens",
        "gutenberg_id": 786,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Brontë Sisters (5) ──────────────────────────────────────────
    "jane-eyre": {
        "title": "Jane Eyre: An Autobiography",
        "author": "Charlotte Brontë",
        "gutenberg_id": 1260,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "villette": {
        "title": "Villette",
        "author": "Charlotte Brontë",
        "gutenberg_id": 9182,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "shirley": {
        "title": "Shirley",
        "author": "Charlotte Brontë",
        "gutenberg_id": 30486,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "wuthering-heights": {
        "title": "Wuthering Heights",
        "author": "Emily Brontë",
        "gutenberg_id": 768,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "tenant-wildfell-hall": {
        "title": "The Tenant of Wildfell Hall",
        "author": "Anne Brontë",
        "gutenberg_id": 969,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Mark Twain (5) ──────────────────────────────────────────────
    "tom-sawyer": {
        "title": "The Adventures of Tom Sawyer",
        "author": "Mark Twain",
        "gutenberg_id": 74,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "huckleberry-finn": {
        "title": "Adventures of Huckleberry Finn",
        "author": "Mark Twain",
        "gutenberg_id": 76,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "connecticut-yankee": {
        "title": "A Connecticut Yankee in King Arthur's Court",
        "author": "Mark Twain",
        "gutenberg_id": 86,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "prince-and-pauper": {
        "title": "The Prince and the Pauper",
        "author": "Mark Twain",
        "gutenberg_id": 1837,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "life-on-mississippi": {
        "title": "Life on the Mississippi",
        "author": "Mark Twain",
        "gutenberg_id": 245,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Oscar Wilde (5) ─────────────────────────────────────────────
    "dorian-gray": {
        "title": "The Picture of Dorian Gray",
        "author": "Oscar Wilde",
        "gutenberg_id": 174,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "importance-being-earnest": {
        "title": "The Importance of Being Earnest",
        "author": "Oscar Wilde",
        "gutenberg_id": 844,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "de-profundis": {
        "title": "De Profundis",
        "author": "Oscar Wilde",
        "gutenberg_id": 921,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "happy-prince": {
        "title": "The Happy Prince, and Other Tales",
        "author": "Oscar Wilde",
        "gutenberg_id": 902,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "soul-of-man": {
        "title": "The Soul of Man under Socialism",
        "author": "Oscar Wilde",
        "gutenberg_id": 1017,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Herman Melville (3) ─────────────────────────────────────────
    "moby-dick": {
        "title": "Moby Dick; Or, The Whale",
        "author": "Herman Melville",
        "gutenberg_id": 2701,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "bartleby": {
        "title": "Bartleby, the Scrivener",
        "author": "Herman Melville",
        "gutenberg_id": 11231,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "typee": {
        "title": "Typee: A Romance of the South Seas",
        "author": "Herman Melville",
        "gutenberg_id": 1900,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Nathaniel Hawthorne (2) ─────────────────────────────────────
    "scarlet-letter": {
        "title": "The Scarlet Letter",
        "author": "Nathaniel Hawthorne",
        "gutenberg_id": 25344,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "house-seven-gables": {
        "title": "The House of the Seven Gables",
        "author": "Nathaniel Hawthorne",
        "gutenberg_id": 77,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Edgar Allan Poe (3) ─────────────────────────────────────────
    "works-poe-raven": {
        "title": "The Works of Edgar Allan Poe (Raven Edition)",
        "author": "Edgar Allan Poe",
        "gutenberg_id": 25525,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "fall-house-usher": {
        "title": "The Fall of the House of Usher",
        "author": "Edgar Allan Poe",
        "gutenberg_id": 932,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "narrative-arthur-pym": {
        "title": "The Narrative of Arthur Gordon Pym",
        "author": "Edgar Allan Poe",
        "gutenberg_id": 51060,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Thomas Hardy (4) ────────────────────────────────────────────
    "tess-durbervilles": {
        "title": "Tess of the d'Urbervilles",
        "author": "Thomas Hardy",
        "gutenberg_id": 110,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "far-madding-crowd": {
        "title": "Far from the Madding Crowd",
        "author": "Thomas Hardy",
        "gutenberg_id": 107,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "mayor-casterbridge": {
        "title": "The Mayor of Casterbridge",
        "author": "Thomas Hardy",
        "gutenberg_id": 143,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "jude-the-obscure": {
        "title": "Jude the Obscure",
        "author": "Thomas Hardy",
        "gutenberg_id": 153,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Joseph Conrad (4) ───────────────────────────────────────────
    "heart-of-darkness": {
        "title": "Heart of Darkness",
        "author": "Joseph Conrad",
        "gutenberg_id": 526,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "lord-jim": {
        "title": "Lord Jim",
        "author": "Joseph Conrad",
        "gutenberg_id": 5658,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "nostromo": {
        "title": "Nostromo",
        "author": "Joseph Conrad",
        "gutenberg_id": 9345,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "secret-agent": {
        "title": "The Secret Agent",
        "author": "Joseph Conrad",
        "gutenberg_id": 23896,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Henry James (3) ─────────────────────────────────────────────
    "portrait-of-lady": {
        "title": "The Portrait of a Lady, Vol. 1",
        "author": "Henry James",
        "gutenberg_id": 2833,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
        "series": "The Portrait of a Lady",
        "series_order": 1,
    },
    "portrait-of-lady-2": {
        "title": "The Portrait of a Lady, Vol. 2",
        "author": "Henry James",
        "gutenberg_id": 2834,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
        "series": "The Portrait of a Lady",
        "series_order": 2,
    },
    "turn-of-screw": {
        "title": "The Turn of the Screw",
        "author": "Henry James",
        "gutenberg_id": 209,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Rudyard Kipling (4) ─────────────────────────────────────────
    "jungle-book": {
        "title": "The Jungle Book",
        "author": "Rudyard Kipling",
        "gutenberg_id": 236,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
        "series": "The Jungle Books",
        "series_order": 1,
    },
    "second-jungle-book": {
        "title": "The Second Jungle Book",
        "author": "Rudyard Kipling",
        "gutenberg_id": 1937,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
        "series": "The Jungle Books",
        "series_order": 2,
    },
    "kim": {
        "title": "Kim",
        "author": "Rudyard Kipling",
        "gutenberg_id": 2226,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "just-so-stories": {
        "title": "Just So Stories",
        "author": "Rudyard Kipling",
        "gutenberg_id": 2781,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Robert Louis Stevenson (3) ──────────────────────────────────
    "treasure-island": {
        "title": "Treasure Island",
        "author": "Robert Louis Stevenson",
        "gutenberg_id": 120,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "jekyll-and-hyde": {
        "title": "The Strange Case of Dr. Jekyll and Mr. Hyde",
        "author": "Robert Louis Stevenson",
        "gutenberg_id": 43,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "kidnapped": {
        "title": "Kidnapped",
        "author": "Robert Louis Stevenson",
        "gutenberg_id": 421,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Victor Hugo (EN translations) (2) ──────────────────────────
    "les-miserables-en": {
        "title": "Les Misérables (English)",
        "author": "Victor Hugo",
        "gutenberg_id": 135,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "hunchback-notre-dame": {
        "title": "The Hunchback of Notre-Dame",
        "author": "Victor Hugo",
        "gutenberg_id": 6539,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Dostoevsky (EN, beyond Crime & Punishment and Brothers K) (5)
    "the-idiot": {
        "title": "The Idiot",
        "author": "Fyodor Dostoevsky",
        "gutenberg_id": 2638,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "notes-from-underground": {
        "title": "Notes from the Underground",
        "author": "Fyodor Dostoevsky",
        "gutenberg_id": 600,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "the-possessed": {
        "title": "The Possessed (Demons)",
        "author": "Fyodor Dostoevsky",
        "gutenberg_id": 8117,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "the-gambler": {
        "title": "The Gambler",
        "author": "Fyodor Dostoevsky",
        "gutenberg_id": 2197,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "poor-folk": {
        "title": "Poor Folk",
        "author": "Fyodor Dostoevsky",
        "gutenberg_id": 2302,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Tolstoy (EN, beyond War&Peace/Anna K/Resurrection/Ivan I) (4)
    "childhood-tolstoy": {
        "title": "Childhood",
        "author": "Leo Tolstoy",
        "gutenberg_id": 2142,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
        "series": "Tolstoy's Trilogy",
        "series_order": 1,
    },
    "boyhood-tolstoy": {
        "title": "Boyhood",
        "author": "Leo Tolstoy",
        "gutenberg_id": 2450,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
        "series": "Tolstoy's Trilogy",
        "series_order": 2,
    },
    "youth-tolstoy": {
        "title": "Youth",
        "author": "Leo Tolstoy",
        "gutenberg_id": 2637,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
        "series": "Tolstoy's Trilogy",
        "series_order": 3,
    },
    "cossacks-tolstoy": {
        "title": "The Cossacks: A Tale of 1852",
        "author": "Leo Tolstoy",
        "gutenberg_id": 4761,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Jack London (4) ─────────────────────────────────────────────
    "call-of-wild": {
        "title": "The Call of the Wild",
        "author": "Jack London",
        "gutenberg_id": 215,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "white-fang": {
        "title": "White Fang",
        "author": "Jack London",
        "gutenberg_id": 910,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "sea-wolf": {
        "title": "The Sea-Wolf",
        "author": "Jack London",
        "gutenberg_id": 1074,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "martin-eden": {
        "title": "Martin Eden",
        "author": "Jack London",
        "gutenberg_id": 1056,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Louisa May Alcott (3) ───────────────────────────────────────
    "little-women": {
        "title": "Little Women",
        "author": "Louisa May Alcott",
        "gutenberg_id": 514,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "little-men": {
        "title": "Little Men",
        "author": "Louisa May Alcott",
        "gutenberg_id": 2788,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
        "series": "Little Women",
        "series_order": 2,
    },
    "jos-boys": {
        "title": "Jo's Boys",
        "author": "Louisa May Alcott",
        "gutenberg_id": 3499,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
        "series": "Little Women",
        "series_order": 3,
    },

    # ── George Eliot (3) ────────────────────────────────────────────
    "middlemarch": {
        "title": "Middlemarch",
        "author": "George Eliot",
        "gutenberg_id": 8227,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "silas-marner": {
        "title": "Silas Marner",
        "author": "George Eliot",
        "gutenberg_id": 9676,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "mill-on-floss": {
        "title": "The Mill on the Floss",
        "author": "George Eliot",
        "gutenberg_id": 6688,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Mary Shelley & Bram Stoker (2) ──────────────────────────────
    "frankenstein": {
        "title": "Frankenstein; Or, The Modern Prometheus",
        "author": "Mary Shelley",
        "gutenberg_id": 84,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
    "dracula": {
        "title": "Dracula",
        "author": "Bram Stoker",
        "gutenberg_id": 345,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },

    # ── Tolstoy — additional lit (1) ────────────────────────────────
    "master-and-man": {
        "title": "Master and Man",
        "author": "Leo Tolstoy",
        "gutenberg_id": 986,
        "voice": "Samantha",
        "language": "en",
        "category": "English Classics",
    },
}
