"""Guided meditation catalog.

Each entry maps a CLI name to metadata used by pure_tone for guided meditation sessions.
Meditations are numbered for easy selection with --mindfulness N.
French versions are stored as {name}-fr.txt and selected with --mindfulness-lang fr.
"""

MEDITATION_CATALOG = {
    # ══════════════════════════════════════
    # ── Buddhism (18) ──
    # ══════════════════════════════════════
    "buddhist-breath-metta": {
        "number": 1,
        "title": "Buddhist Breath & Metta Meditation",
        "author": "Thanissaro Bhikkhu",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "metta": {
        "number": 2,
        "title": "Lovingkindness (Metta) Meditation",
        "author": "Palouse Mindfulness",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "vipassana": {
        "number": 3,
        "title": "Vipassana Insight Meditation",
        "author": "Traditional",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "anapanasati": {
        "number": 4,
        "title": "Anapanasati Sutta — 16 Steps of Breath",
        "author": "Majjhima Nikaya 118 (tr. Thanissaro Bhikkhu)",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "loving-kindness": {
        "number": 5,
        "title": "Loving-Kindness Meditation",
        "author": "Greater Good Science Center, UC Berkeley",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "impermanence": {
        "number": 6,
        "title": "Contemplation of Impermanence",
        "author": "Traditional Buddhist",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "tonglen": {
        "number": 7,
        "title": "Tonglen Compassion Practice",
        "author": "Tibetan Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "equanimity": {
        "number": 8,
        "title": "Equanimity (Upekkha) Meditation",
        "author": "Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "sympathetic-joy": {
        "number": 9,
        "title": "Sympathetic Joy (Mudita) Meditation",
        "author": "Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "death-contemplation": {
        "number": 10,
        "title": "Mindfulness of Death (Maranasati)",
        "author": "Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "satipatthana-body": {
        "number": 11,
        "title": "Satipatthana Body Meditation",
        "author": "Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "mindfulness-feelings": {
        "number": 12,
        "title": "Mindfulness of Feelings (Vedananupassana)",
        "author": "Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "zen-sitting": {
        "number": 13,
        "title": "Zen Sitting (Zazen / Shikantaza)",
        "author": "Zen Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "calm-abiding": {
        "number": 14,
        "title": "Calm Abiding (Samatha) Meditation",
        "author": "Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "four-elements": {
        "number": 15,
        "title": "Four Elements Meditation",
        "author": "Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "refuge": {
        "number": 16,
        "title": "Taking Refuge Meditation",
        "author": "Buddhist Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "ho-oponopono": {
        "number": 17,
        "title": "Ho'oponopono Hawaiian Healing",
        "author": "Hawaiian Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    "forgiveness": {
        "number": 18,
        "title": "Forgiveness Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Buddhism",
    },
    # ══════════════════════════════════════
    # ── Yoga (12) ──
    # ══════════════════════════════════════
    "yoga-nidra": {
        "number": 19,
        "title": "Yoga Nidra in Nature",
        "author": "Jennie Wadsten / YogaLeela",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "yoga-nidra-relaxation": {
        "number": 20,
        "title": "Yoga Nidra for Deep Relaxation",
        "author": "Yin and Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "yoga-nidra-deep": {
        "number": 21,
        "title": "Deep Yoga Nidra (Extended Session)",
        "author": "Yoga Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "chakra": {
        "number": 22,
        "title": "Guided Chakra Meditation",
        "author": "Do-Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "chakra-awareness": {
        "number": 23,
        "title": "Chakra Awareness Meditation",
        "author": "Traditional Yoga",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "savasana": {
        "number": 24,
        "title": "Guided Savasana Relaxation",
        "author": "Vedic Yoga Academy",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "prana-breath": {
        "number": 25,
        "title": "Pranayama Breath Meditation",
        "author": "Traditional Yoga",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "kundalini": {
        "number": 26,
        "title": "Kundalini Awakening Meditation",
        "author": "Yoga Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "heart-opening": {
        "number": 27,
        "title": "Heart Opening Meditation",
        "author": "Yoga Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "third-eye": {
        "number": 28,
        "title": "Third Eye (Ajna) Meditation",
        "author": "Yoga Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "nadi-shodhana": {
        "number": 29,
        "title": "Alternate Nostril Breathing (Nadi Shodhana)",
        "author": "Pranayama Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    "om-meditation": {
        "number": 30,
        "title": "OM Vibration Meditation",
        "author": "Yoga Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Yoga",
    },
    # ══════════════════════════════════════
    # ── Mindfulness (10) ──
    # ══════════════════════════════════════
    "body-scan": {
        "number": 31,
        "title": "Body Scan Meditation",
        "author": "Yoga Jala",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    "mindful-breathing": {
        "number": 32,
        "title": "Guided Mindfulness Breathing",
        "author": "Do-Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    "mindful-breathing-va": {
        "number": 33,
        "title": "Mindful Breathing (VA Public Domain)",
        "author": "Shilagh Mirgain, PhD / US Veterans Health",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    "breath-awareness": {
        "number": 34,
        "title": "Breath Awareness Meditation",
        "author": "Traditional Mindfulness",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    "present-moment": {
        "number": 35,
        "title": "Present Moment Awareness",
        "author": "Traditional Mindfulness",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    "grounding": {
        "number": 36,
        "title": "Grounding Meditation for Anxiety",
        "author": "Therapeutic Mindfulness",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    "rain-meditation": {
        "number": 37,
        "title": "RAIN Meditation (Recognize, Allow, Investigate, Nurture)",
        "author": "Inspired by Tara Brach",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    "progressive-relaxation": {
        "number": 38,
        "title": "Progressive Muscle Relaxation",
        "author": "Therapeutic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    "safe-place": {
        "number": 39,
        "title": "Safe Place Visualization",
        "author": "Therapeutic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    "acceptance": {
        "number": 40,
        "title": "Acceptance Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Mindfulness",
    },
    # ══════════════════════════════════════
    # ── Spiritual (14) ──
    # ══════════════════════════════════════
    "gratitude": {
        "number": 41,
        "title": "Deep Gratitude Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "self-compassion": {
        "number": 42,
        "title": "Self-Compassion Meditation",
        "author": "Inspired by Kristin Neff",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "inner-child": {
        "number": 43,
        "title": "Inner Child Healing Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "divine-light": {
        "number": 44,
        "title": "Divine Light Meditation",
        "author": "Spiritual Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "letting-go": {
        "number": 45,
        "title": "Letting Go Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "surrender": {
        "number": 46,
        "title": "Surrender and Trust Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "abundance": {
        "number": 47,
        "title": "Abundance Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "peace-within": {
        "number": 48,
        "title": "Inner Peace Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "sacred-heart": {
        "number": 49,
        "title": "Sacred Heart Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "spiritual-awakening": {
        "number": 50,
        "title": "Spiritual Awakening Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "unity-consciousness": {
        "number": 51,
        "title": "Unity Consciousness Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "prayer-of-the-heart": {
        "number": 52,
        "title": "Contemplative Prayer (Centering Prayer)",
        "author": "Christian Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "sacred-silence": {
        "number": 53,
        "title": "Sacred Silence Meditation",
        "author": "Contemplative Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    "cosmic-breath": {
        "number": 54,
        "title": "Cosmic Breath Meditation",
        "author": "Spiritual Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Spiritual",
    },
    # ══════════════════════════════════════
    # ── Therapeutic (10) ──
    # ══════════════════════════════════════
    "mountain": {
        "number": 55,
        "title": "Mountain Meditation",
        "author": "Inspired by Jon Kabat-Zinn",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    "lake": {
        "number": 56,
        "title": "Lake Meditation",
        "author": "Mindfulness Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    "ocean": {
        "number": 57,
        "title": "Ocean Meditation",
        "author": "Mindfulness Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    "sleep": {
        "number": 58,
        "title": "Sleep Meditation",
        "author": "Therapeutic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    "morning": {
        "number": 59,
        "title": "Morning Awakening Meditation",
        "author": "Therapeutic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    "confidence": {
        "number": 60,
        "title": "Confidence Meditation",
        "author": "Therapeutic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    "emotional-release": {
        "number": 61,
        "title": "Emotional Release Meditation",
        "author": "Somatic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    "stress-release": {
        "number": 62,
        "title": "Stress Release Body Scan",
        "author": "Therapeutic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    "resilience": {
        "number": 63,
        "title": "Resilience Meditation",
        "author": "Therapeutic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    "pain-management": {
        "number": 64,
        "title": "Pain Management Meditation",
        "author": "Therapeutic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Therapeutic",
    },
    # ══════════════════════════════════════
    # ── Healing (6) ──
    # ══════════════════════════════════════
    "healing-light": {
        "number": 65,
        "title": "Healing Light Meditation",
        "author": "Healing Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Healing",
    },
    "body-love": {
        "number": 66,
        "title": "Body Appreciation Meditation",
        "author": "Somatic Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Healing",
    },
    "cellular-healing": {
        "number": 67,
        "title": "Cellular Healing Meditation",
        "author": "Healing Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Healing",
    },
    "energy-cleansing": {
        "number": 68,
        "title": "Energy Cleansing Meditation",
        "author": "Healing Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Healing",
    },
    "golden-light-scan": {
        "number": 69,
        "title": "Golden Light Body Scan",
        "author": "Healing Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Healing",
    },
    "earth-connection": {
        "number": 70,
        "title": "Earth Connection Grounding",
        "author": "Healing Tradition",
        "language": "en",
        "voice": "Samantha",
        "category": "Healing",
    },
    # ══════════════════════════════════════
    # ── Nature (12) ──
    # ══════════════════════════════════════
    "forest-bathing": {
        "number": 71,
        "title": "Forest Bathing (Shinrin-yoku)",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "starlight": {
        "number": 72,
        "title": "Starlight Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "garden": {
        "number": 73,
        "title": "Secret Garden Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "river": {
        "number": 74,
        "title": "River Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "waterfall": {
        "number": 75,
        "title": "Waterfall Purification Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "ocean-depths": {
        "number": 76,
        "title": "Ocean Depths Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "sunset": {
        "number": 77,
        "title": "Sunset Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "moonlight": {
        "number": 78,
        "title": "Moonlight Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "meadow": {
        "number": 79,
        "title": "Meadow Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "rain-forest": {
        "number": 80,
        "title": "Rainforest Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "mountain-lake": {
        "number": 81,
        "title": "Mountain Lake Meditation",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
    "spring-garden": {
        "number": 82,
        "title": "Spring Garden Awakening",
        "author": "Nature Meditation",
        "language": "en",
        "voice": "Samantha",
        "category": "Nature",
    },
}

# Number-to-name lookup
MEDITATION_BY_NUMBER = {m["number"]: name for name, m in MEDITATION_CATALOG.items()}

MEDITATION_CATEGORIES = [
    "Buddhism",
    "Yoga",
    "Mindfulness",
    "Spiritual",
    "Therapeutic",
    "Healing",
    "Nature",
]
